db/seeds.rb

@martinhoaragao Can you check if these are the names you want? I'm also wondering if you wish to create a `acronym` attribute that would be useful for departments like DREP and CAOS 🤔

Create Department seeds.

---

app/controllers/users_controller.rb

* Clerance was already remove but this was left behind. Somehow, when
running on a local machine no error was shown, but when runninng on the
remote server the app would not run due to this.

Remove UsersController inheriting from Clearance::UsersController.

---

app/assets/stylesheets/landing_page/style.scss
app/views/layouts/lp/_navbar.html.slim
app/views/sessions/new.html.slim

* Remove login form and add three authentication links, Facebook, Gmail
(Google) or Github.
* Update landing_page/style.scss removing uneeded/unused styles for
.login-form class.

Update Log In screen.

---

app/views/activities/_form.slim
app/views/activities/show.slim

* Remove :registration_link from activies form.
* Update activities/show to check if there's a user currently logged in
before checking if the user is already registered in the activity.

Update activities views.

---

Capfile
Gemfile
Gemfile.lock
config/puma.rb

Replace thin/webrick with puma

---

app/views/layouts/lp/_navbar.html.slim

1. Move envs to shared file through Capistrano
Previously the .env file would have to be restored after each deployment. 
Moving it to the capistrano's shared folder simplifies the process.
2. Hide login and logout views
Latest commits have not been deployed due to the complications of releasing these actions.
May open this as 2 PRs, yet I felt opening a PR to hide views, when previous commits haven't been deployed for it felt counter-productive. Instead, I would not squash these commits to simplify revert.

Fix envs file and prepare deployment

---

app/assets/stylesheets/_activities.scss
app/views/users/show.slim

This is really really just a minimal profile page. I'm just opening this for two reasons:
- We're gonna need a profile page if users are going to register themselves (and there was none)
- Profile pages are going to be linked in a activity `show` page were a user is registered
This closes #78 .

Add minimal profile page.

---

app/assets/stylesheets/_activities.scss
app/models/activity.rb
app/views/activities/show.slim

This PR only adds a "edit activity" button which is only visible to members who can edit an activity. I didn't include a "delete activity" button because there's already a button on the edit form to that end.

Adds edit activity button

---

app/assets/stylesheets/welcome.scss
app/controllers/activities_controller.rb
app/helpers/activities_helper.rb
app/views/activities/_form.slim
app/views/activities/index.slim
app/views/activities/show.slim
app/views/layouts/lp/_navbar.html.slim

This PR adds the following changes:
- Adds a "Atividades" option on the navbar
- Adds a "Criar Atividade" button that only shows to users who have the ability to create activities. 
- Fixes minor bugs

Adds create activity button

---

app/views/layouts/lp/_footer.html.slim

The calendar is now linked in Cesium's website

Added MiEI calendar's link to the footer

---

app/views/activities/index.slim

Before alignment:
After alignment:

Align activities menu with the global container

---

app/views/layouts/lp/_navbar.html.slim
config/routes.rb

This PR just adds a link to `cesium.di.uminho.pt/noticias` to the navbar.

Adds news link to navbar

---

app/assets/stylesheets/landing_page/_footers.scss
app/assets/stylesheets/variables.scss
app/views/layouts/lp/_footer.html.slim

I think it looks nicer in all platforms.

Improved heart in footer look

---

public/partners.yml

Bachio's partnership is wrong. This PR should fix it.

Fixes bachio's partnership

---

Gemfile
Gemfile.lock

It's the last gem that needs to be fixed for https://github.com/cesium/atomic/issues/147

Update paperclip in order to fix a security vulnerability.

---

app/helpers/activities_helper.rb
app/views/activities/_registration.slim

Fixes https://github.com/cesium/atomic/issues/155

Fix registration button

---

.rubocop.yml
.travis.yml

Fixes https://github.com/cesium/atomic/issues/148

Add travis

---

app/views/activities/show.slim
app/views/shared/activity/_description_date.slim
app/views/shared/activity/_panel.slim

Couldn't reproduce the issue but I think this fixes #167

fix nil speaker error

---

app/assets/stylesheets/landing_page/_base.scss
app/assets/stylesheets/landing_page/_footers.scss

The footer was broken on master ¯\_(ツ)_/¯

Revert changes from #182

---

app/views/welcome/team.html.slim
public/team.json

As requested by @FranciscoLira

Categorize display of team members

---

.travis.yml
config/database.yml

Read more [here](https://docs.travis-ci.com/user/database-setup/#postgresql).

Fix Travis pipeline

---

app/views/articles/_articles_breadcrumb.slim

I noticed all other pages were in Portuguese. I think it's better to make it more consistent.

Translate articles to pt

---

.travis.yml
Gemfile
Gemfile.lock

- https://stackoverflow.com/questions/66785194/what-happened-to-mimemagic
- https://github.com/rails/rails/issues/41757#issuecomment-808024283

Fix travis build
